INSERT INTO type 
VALUES ('1', 'Permissions for Sales Clerk', 'SALES_CLERK_PERMISSION', ' ')

INSERT INTO type 
VALUES ('2', 'Permissions for Specialist', 'SPECIALIST_PERMISSION', ' ')

INSERT INTO type 
VALUES ('3', 'Permissions for Operations Manager', 'OPERATIONS_MANAGER_PERMISSION', ' ')

INSERT INTO type 
VALUES ('4', 'Permissions for Sales Clerk', 'SALES_CLERK_PERMISSION', ' ')

INSERT INTO type 
VALUES ('5', 'Payment Not Received', 'PAYMENT_NONE', ' ')

INSERT INTO type 
VALUES ('6', 'Partial Payment Received', 'PAYMENT_PARTIAL', ' ')

INSERT INTO type 
VALUES ('7', 'Payment Received in Full', 'PAYMENT_FULL', ' ')

INSERT INTO type 
VALUES ('8', 'Sales Clerk', 'TYPE_SALES_CLERK', ' ')

INSERT INTO type 
VALUES ('9', 'Specialist', 'TYPE_SPECIALIST', ' ')

INSERT INTO type 
VALUES ('10', 'Operations Manager', 'TYPE_OPERATIONS_MANAGER', ' ');

INSERT INTO type 
VALUES ('11', 'Print Job', 'TYPE_JOB_PRINT', '39.99 ');

INSERT INTO type 
VALUES ('12', 'Engrave Job', 'TYPE_ENGRAVE_JOB', '69.99');

INSERT INTO type 
VALUES ('13', 'T-Shirt', 'TYPE_MEDIA_TSHIRT', '12.99 ');

INSERT INTO type 
VALUES ('14', 'Paper', 'TYPE_MEDIA_PAPER', '0.10 ');

INSERT INTO type 
VALUES ('15', 'Trophy', 'TYPE_MEDIA_TROPHY', '45.99');

INSERT INTO type 
VALUES ('16', 'Plaque', 'TYPE_MEDIA_PLAQUE', '85.99 ');

INSERT INTO type 
VALUES ('17', 'Order Validated', 'TYPE_ORDER_VALID', ' ');

INSERT INTO type 
VALUES ('18', 'Order Pass QA', 'TYPE_QA_PASS', ' ');

INSERT INTO type 
VALUES ('19', 'Order Fail QA', 'TYPE_QA_FAIL', ' ');

INSERT INTO type 
VALUES ('20', 'Work Complete', 'TYPE_WORK_COMPLETE', ' ');

INSERT INTO type 
VALUES ('21', 'Order Ready for Delivery', 'TYPE_ORDER_READY_DELIVER', ' ');

